### PR TITLE
Adding Mitar to mentors.

### PR DESCRIPTION
**Pull request by toshitabarve**
Have added Mitar to mentors along with all the links.

### CODE REVIEW

**Comment by roonyh** [comment]
Thanks. But you need to update your fork and rebase this work on top of updated master branch. I know that should be a little confusing. :) But let us help you.

So since @namangoel1 rebased your earlier commits this is a bit of a special case.

First this is much easier if you use git bash.

Add the upstream repos as a remote: `git remote add upstream https://github.com/fossasia/fossasia.github.io.git`

Back up your files. Copy files you changed to some other location.

Reset your branch to look just like upstream.

`git reset --hard upstream/master`

Now take your changes from backed up files. Apply them. Commit again. Push and submit pull request.

@namangoel1 @samarjeet27 @pwmvx1289 could help you should you need any.

**Comment by toshitabarve** [comment]
When I tried 
`git reset --hard upstream/master`
It gave me this error:
`fatal: ambiguous argument 'upstream/master' : unknown revision or a path not in the working tree.`
Please help. @namangoel1 @RoonyH @samarjeet27 @pwmvx1289

**Comment by roonyh** [comment]
oh. I think after  `git remote add upstream https://github.com/fossasia/fossasia.github.io.git`
you need to do `git fetch upstream master`. Sorry I forgot that step.

see https://help.github.com/articles/syncing-a-fork/ and https://www.youtube.com/watch?v=-zvHQXnBO6c to understand what we are doing here.

**Comment by wongalvis** [comment]
Sorry I didn't notice this.
You should follow @RoonyH 's instructions and then do a rebase or merge. Google these commands and if you still have problems feel free to leave a comment.
Good luck. :)

**Comment by samarsault** [comment]
Hi, @toshitabarve check this https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by roonyh** [comment]
Closing due to inactivity. Please open another when you are ready.

**Pull request closed without merging**
