### PR TITLE
Improving with bootstrap v2

### PR DESCRIPTION
**Pull request by mbelchev**
I think i am ready, but any feedback is welcome.

### CODE REVIEW

**Comment by mbelchev** [comment]
I forgot to say that if you accept my design next students have to build over this template. As i said in the last request i rewrite whole structure. Thank you!

**Comment by roonyh** [comment]
Thank you but rewriting the whole structure in one commit is not right. We will lose our recent work from it. Only adding that bouncing down animation will be enough for this task. Its great that you tried to make it responsive but we need to bring in that change delicately little by little :)

I will add more tasks about responsiveness of this site and that way you get to complete more tasks too. Please add only the bouncing animation and nothing else in a commit. So that we can bring it in seamlessly. I am terrible sorry about not bringing this in in one go.

Thank you very much for your hard work!

**Comment by mbelchev** [comment]
Well, I understand now. You want to improve the web site step by step and everyone to take part in the project. Sorry about my requests and wasting your time, but i was confused by my task description. 

Tommorow will sent you only the animation for my current Google assigment and after that if you accept it i can pick another task to continue improving Fossasia's web page. :)

Thanks!

**Comment by roonyh** [comment]
You absolutely most definitely did not waste my time!! I enjoy working with you kids :smile: If anybody waste anybody's time its me your time. Thanks for understanding and sorry about the confusion.

**Comment by roonyh** [comment]
closing since #36 is merged

**Pull request closed without merging**
