### PR TITLE
Added Twitter Timeline (Feed)

### PR DESCRIPTION
**Pull request by PolBaladas**
I've added the twitter timeline(feed) section on the web page and inserted it.

### CODE REVIEW

**Comment by roonyh** [comment]
Nice! Can you try and place it side by side with the list of contributors?

**Comment by roonyh** [comment]
I close this anyway since you have completed the requirements of the task.

**Comment by PolBaladas** [comment]
Fine, Thanks.
I will modify and put it side by side with the contributors (left or
right?) when I get home. Mark it as closed, thanks.

I close this anyway since you have completed the requirements of the task.

**Comment by roonyh** [comment]
Twitter feed looks nicer now. No further work needed.

**Comment by PolBaladas** [comment]
Ok. No problem, if you want any further additions to it just tell me.
Thanks.

**Pull request merged**
