### PR TITLE
added student

### PR DESCRIPTION
**Pull request by MarioScappini**

### CODE REVIEW

**Comment by namangoel1** [comment]
@MarioScappini Please update your repository first. You're working on a very old version of the site.

@RoonyH can't merge yet heh.

**Comment by MarioScappini** [comment]
sorry but how i do that?

**Comment by roonyh** [comment]
Hi. You can look at https://help.github.com/articles/syncing-a-fork/

And Guidelines for adding images are changed a bit. https://github.com/fossasia/fossasia.github.io/wiki/Installing-GitHub-And-Adding-Images

@samarjeet27 @namangoel1 please help out @MarioScappini if he needs.

**Comment by MarioScappini** [comment]
i think was able to update can you check it please

**Comment by namangoel1** [comment]
@MarioScappini, doesn't look like anything changed. Please sync your fork, follow the guidelines RoonyH linked, and create a new pull request. Close this one.

Thanks!

**Pull request closed without merging**
