### PR TITLE
Added Youtube and Wikipedia link and images

### PR DESCRIPTION
**Pull request by wongalvis**

### CODE REVIEW

**Comment by namangoel1** [comment]
@pwmvx1289 Don't you think the images are too large to be icons of 48*48? Secondly, have you merged the current version of the repository? Not sure why you need to remove the stylesheet manually in the commit.

**Comment by wongalvis** [comment]
@namangoel1 When I merge I didn't take well care of the conflict on the file, so I'm removing it manually. I hope it's not causing trouble.

**Comment by tradzik** [comment]
I think actions by @pwmvx1289  are unfair. He is finishing tasks, without claiming them and makes other students to get assigned! 
@fossasia/owners  please do something with that!

**Comment by roonyh** [comment]
@pwmvx1289 is submitting a pull request to an open source software. He does not mention a task. So in that sense he is doing nothing unfair. So since the work of this task (http://www.google-melange.com/gci/task/view/google/gci2014/5804339213893632) is done here (we just need to merge) I will freeze that task. Nobody will be assigned to it. How does that sound? Is that fair? 
Ideally I would like to see all of you contributing wherever possible without concerning about tasks. But that is not practical. Above is the closest I can get to that.

**Comment by tradzik** [comment]
@roonyh Ok, I understand. I will contribute to every repo, I am glad AW is
contributing. I just mentioned that the tasks are now unusable...
Please don't understand me bad

**Comment by wongalvis** [comment]
@ty221 I'm sorry if I'm causing trouble. I'm just trying to contribute more in all means of work e.g. improving the UI of the leaderboard. Before I was leaving a message saying that I would like to work on it without claiming it at first, I was just trying to avoid duplicated work and never meant to "reserve" the task. Sorry about that. Now I'm doing contribution in more kinds of way, since UI/UX and design are the areas that I'm most fond of, so I am doing more of them.
My idea to add the icons and links asap is to keep the webpage updated, since FOSSASIA now has a Youtube channel and should be announced by public means.

**Comment by roonyh** [comment]
@pwmvx1289 @ty221 None of you are causing troubles. :) We are thankful for your enthusiasm in contributing to this project. Just be co-operative and reasonable when you do so.

**Comment by wongalvis** [comment]
I'm aware of the problem that the icons are not displaying properly and I'll fix it asap soon.

**Comment by roonyh** [comment]
I reverted this for now. Since there is a problem with images rendering. @pwmvx1289 thanks for working on it.

**Pull request merged**
