### PR TITLE
Fixing issues pointed out by Amirul

### PR DESCRIPTION
**Pull request by namangoel1**
Fixing [#23](https://github.com/fossasia/fossasia.github.io/issues/23) and [#26](https://github.com/fossasia/fossasia.github.io/issues/26)

### CODE REVIEW

**Comment by namangoel1** [comment]
@RoonyH Any update here? Thanks!

**Comment by roonyh** [comment]
@namangoel1 Oh. sorry about not attending to this sooner. Got a lot of pull requests here in addition to my actual job :smile: Didn't had much time. #23 is fixed in another commit. Don't worry much about #26 for now, focus on your task. Are you waiting for a review?

**Comment by namangoel1** [comment]
@RoonyH Haha, glad all is fixed :)

Got the pox suddenly and wasn't able to work :( will hope to wrap up my current task by today, though. Thanks!

**Comment by roonyh** [comment]
@namangoel1 :worried: Hope you'll get a faster recovery!

**Comment by namangoel1** [comment]
Should be a simple merge @RoonyH  ;) fixed a lot of things and cleaned up code.

**Comment by roonyh** [comment]
Thank you very much for taking time to do these!! Very welcome changes! But the footer doesn't look nice now. Can you please keep the horizontal format with social media/ events and links. And why remove that twitter bird? I thought it was nice :cry: You don't like it?

**Comment by namangoel1** [comment]
@RoonyH  Fixed the footer.

About the twitter bird... Well my only rationale was that it's a render of the times of the old logo. IIRC the TOS disallows such things now. I can add that back if you wish, though.

This is all presentable right now, though; all merge ready.

Thanks!

**Pull request merged**
