### PR TITLE
Added meta tags

### PR DESCRIPTION
**Pull request by wongalvis**

### CODE REVIEW

**Comment by tradzik** [comment]
Hello!
To are 4 required Open Graph parameters:

og:title - The title of your object as it should appear within the graph, e.g., "The Rock".
og:type - The type of your object, e.g., "video.movie". Depending on the type you specify, other properties may also be required.
og:image - An image URL which should represent your object within the graph.
og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".

You didn't add og:url. Please do that and commit your changes. Thanks!

**Comment by wongalvis** [comment]
@ty221 Setting og:url will cause all web info and meta tags content to be fetched from the canonical URL, the link will also be directed to the url. Since we are all making the sites under different github.io addresses, I didn't set a fixed one.

Try it here: https://developers.facebook.com/tools/debug/og/object?q=opengraphprotocol.org
original    http://opengraphprotocol.org/
og:url  http://ogp.me/
The following will be treated as a redirect by the crawler:
A HTTP redirect
A <link rel="canonical" href=".." /> tag
A <meta property="og:url" content=".." /> tag
The final URL, which we tried to extract metadata from is highlighted in bold

**Comment by tradzik** [comment]
Yes I do. They are helpful, e.g. for Facebook. However, doc is doc and you
have to meet its requirments

**Comment by wongalvis** [comment]
@ty221 I strongly recommend you to spend a few minutes trying out the og debugger.

**Comment by tradzik** [comment]
Please give me link to doc, which tells, you can skip og:url meta tag.

**Comment by wongalvis** [comment]
Firstly, open graph won't fail to work if certain tags are missing, otherwise there will be only some websites that are capable of being shared on Facebook.

In https://developers.facebook.com/tools/debug/og/object/?q=pwmvx1289.github.io/fossasia10, Warnings That Should Be Fixed
Inferred Property   The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags.

og:url is not provided since, as I mentioned in previous comments, we all have the site under different github.io domains, setting it as fixed will cause troubles when we share our own sites.

It is totally working as shown in the debugger, or you can see the preview when you paste the url in Facebook status.

**Comment by tradzik** [comment]
Thank you for explaintation. I understand it, and agree with it in genral.

However, I still belive our website shouldnt contain any error and warnings
during debugging  - why? Because code must be clear; errors on website make
it less interesting for scrawler bots...

I think Jekyll has property/variable, which contains current URL of website
(might be needed to connect some of them). Please research that and use
that as content of og:url tag - then shouldnt be any troubles. Or maybe do
you have other idea? Eventually I can even merge your PR with warnings if
you show, it could cause serious troubles for our other sites or isn't
easliy fixable.

**Comment by wongalvis** [comment]
I can't find the suitable variable here http://jekyllrb.com/docs/variables/

**Comment by wongalvis** [comment]
After testing for times I couldn't manage to find the right variable.

**Comment by tradzik** [comment]
Hmm.... After looking in Internet, I found this combination as it might be
helpful - {{ site.baseurl }}{{ page.url }}
Can you test it please or something similar to it?

Sun Jan 25 2015 at 10:59:44 użytkownik pwmvx1289 notifications@github.com
napisał:

**Comment by wongalvis** [comment]
I tried, doesn't work.

**Comment by tradzik** [comment]
Please give me a second to research

Sun Jan 25 2015 at 11:02:24 użytkownik pwmvx1289 notifications@github.com
napisał:

**Comment by tradzik** [comment]
I found the solution. Please follow this tutorial: http://www.jaredwolff.com/blog/jekyll-local-preview/

instead of post.url use page.url

You don't need to set up local preview, nobody is in general interested in OG tags :p 
Best luck!

**Comment by wongalvis** [comment]
This doesn't solve the problem, as I mentioned for several times, we all have the site under different github.io domains, setting it as fixed will cause troubles when we share our own sites.

**Comment by tradzik** [comment]
Can you give an example? Please explain what will happen. It we set up OG
tags for each website, there wouldnt be any problem (I may be wrong)

Sun Jan 25 2015 at 11:15:34 użytkownik pwmvx1289 notifications@github.com
napisał:

**Comment by wongalvis** [comment]
No there wouldn't be any problem, but all individuals who would like to share their own fossasia code-in site have to change their own og:url, and that the warning could be totally ignored.

**Comment by tradzik** [comment]
@pwmvx1289 You are unpleasant now. Let us talk up to the mark. Please explain me, give example, etc. what problems will happen if we will set up this as fixed. Then I will approve your pull request.

**Comment by wongalvis** [comment]
I've clearly explained what are the problems and their effects, I also provided examples in the og debugger, you should really spend some minutes to visit the debugger, read the docs, if you still have any problems understanding you can ask me.

**Comment by tradzik** [comment]
If you don't want to discuss, please wait for other mentor to review it. I won't approve pull request with warnings unless you show there are unfixable. I've removed my assignment.

 I think other mentors also want to have clean code. I asked you many times, which troubles will cause adding fixed URL to og:url parameter - you didn't explain that. I will give you an example:
1. on fossasia.github.io is fixed og:url to "http://fossasia.github.io"
2. I want to share e.g. fossasia.github.io/fossasia10 link. It doesn't contain og:url. Facebook will get default data of the page filling it by URL, first-found image, etc. 

Where is the problem?

**Comment by wongalvis** [comment]
Using your example, if og:url is fixed to "http://fossasia.github.io", and I have pwmvx1289.github.io/fossasia.github.io and want to share my site, I have to change the og:url. This doesn't only apply to me but all individuals who would like to share their own fossasia code-in site. If og:url is not set, Facebook will automatically set the URl to the shared URL, other parameters such as image, description, etc. are not affected.

**Comment by tradzik** [comment]
ok @pwmvx1289 eventually you explained that clearly. Let us suppress this warning. I will merge your pull request. Thank you for your changes!

**Comment by wongalvis** [comment]
@ty221 The only solution to suppress the warning is to provide the URL dynamically, one simple approach is to use PHP (I guess you already know that).

**Comment by tradzik** [comment]
@pwmvx1289 Yes I know that. Let us keep that 'as is'. Thank you for your edits

**Comment by roonyh** [comment]
Thank you both for working on improving this project.

Tymon, please don't get all bossy and say stuff like "I will not
approve..". We are all collaborators. Nothing more.

**Comment by wongalvis** [comment]
@RoonyH I understand what he means, we are all good. Thanks and cheers :-)

**Comment by tradzik** [comment]
@RoonyH I am glad we could help. 

I told that ("I will not approve"), because I don't like merging pull requests, which are not ideal (I mean they contain warnings, etc.). I am not bossy, just wanted to @pwmvx1289 give me rational arguments, why should we suppress this warnings. Write access is big responsibility. I am just collaborator and wanted to know, which problems could setting-up og:url cause. 

I think me and @pwmvx1289  are both good ;-)

Cheers!

**Pull request merged**
