### PR TITLE
Image existence test and fixing issues

### PR DESCRIPTION
**Pull request by namangoel1**
automatically run by travis to check if there's some file mentioned in the json files that does not exist in images directory.

### CODE REVIEW

**Comment by namangoel1** [comment]
@RoonyH Can this be merged?

**Comment by namangoel1** [comment]
This now fixes #237 and #238 

@RoonyH let me know if it's okay to merge.

**Comment by roonyh** [comment]
Ah. I haven't check this yet. The problem I saw on the first look is this
goes through the images list for a second time. I would like to have both
tests we have, imagesize and this, to do it in one go. Anyway we will get
to it later. Please merge if Travis is green.

Have you worked with git branches? You can work in different git branches
which allows you to submit separate pull requests for separate work. Which
avoids conflicts like these.

**Comment by namangoel1** [comment]
@RoonyH Understood, you're correct. I'll merge and then work on combining the two. 

Didn't know about that, will do. Thanks!

**Pull request merged**
