### PR TITLE
Adding photo and greeting in one more language.

### PR DESCRIPTION
**Pull request by 3phase**
I've added my picture as well as greeting in Bulgarian.

### CODE REVIEW

**Comment by roonyh** [comment]
Thanks! For your image to show up in nice shape we need it to be of square shape. (1:1). Can you please make it 300px*300px?

**Comment by 3phase** [comment]
It is 1:1 (600 x 600) now, so it's square shape. 
Do you need it to be exactly 300x300? I've tried scaling the image down to the specified dimensions, but it was breaking the rows after me. That's why I returned to the size which the first of the students had used.

**Comment by roonyh** [comment]
600px*600px is fine!

**Comment by roonyh** [comment]
Please push another commit with the change. :smile:

**Comment by 3phase** [comment]
I will, I'm trying to figure out the reason why the pushed image is not the in the dimension in which it is in my drive :D

**Comment by 3phase** [comment]
Gotta be OK now. Hate this Bash-like stupidity I'm pushing with for Windows :D

**Comment by roonyh** [comment]
Did you claim a task for this? Can you give me the link?

**Comment by 3phase** [comment]
Yea, I claimed one. Here is the link: http://www.google-melange.com/gci/task/view/google/gci2014/6394271980584960

**Comment by roonyh** [comment]
great! please submit a link to this pull request and mark it as finished.

**Pull request merged**
