### PR TITLE
JSCS validateIndentation

### PR DESCRIPTION
**Pull request by samarsault**
Enforce validateIndentation to accept only 2 spaces for indentation and lint main.js according to that

### CODE REVIEW

**Comment by namangoel1** [comment]
Can you link your task please?

**Comment by samarsault** [comment]
https://www.google-melange.com/gci/task/view/google/gci2014/5257295269199872
Here you go

**Comment by samarsault** [comment]
btw why's the build's failing ??

**Comment by namangoel1** [comment]
@samarjeet27 Thank you! 

As you can see, both builds fail. Please rename ".jscs.json" to ".jscsrc" and run locally before pushing.

**Comment by samarsault** [comment]
@namangoel1 renamed and runs fine locally !

**Comment by namangoel1** [comment]
Thank you! Are there any style errors in JS pointed out by JSCS? I'm waiting for Travis' logs, but it seems that this fails again.

**Comment by namangoel1** [comment]
@samarjeet27 Still seems to be a problem... are you sure that it runs fine locally? See https://travis-ci.org/fossasia/fossasia.github.io/jobs/45917746#L297

**Comment by namangoel1** [comment]
As you can see, [travis still fails](https://travis-ci.org/fossasia/fossasia.github.io/jobs/45918539). Have you checked locally properly?

**Comment by roonyh** [comment]
@samarjeet27 I have messed up in that tasks description. I am sorry :cry:

we need to edit a `.jscsrc` file not `.jscs.json`. i see that @namangoel1 has updated this. Can you please [update your fork](http://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository) and resubmit your pull request?

this is really due to my error. I am sorry again.

**Comment by samarsault** [comment]
Check https://github.com/fossasia/fossasia.github.io/pull/222

**Pull request closed without merging**
