### PR TITLE
Display smaller header images for mobile devices

### PR DESCRIPTION
**Pull request by wongalvis**

### CODE REVIEW

**Comment by namangoel1** [comment]
@pwmvx1289 thanks! This is quite a large change and has been merged with the previous version of the site. Hope it does not cause much problems.

**Comment by wongalvis** [comment]
@namangoel1 This changes in this PR is merged?

**Comment by namangoel1** [comment]
@pwmvx1289 Not yet, the changes you've made in 0ac21f5 are causing problems. Working on fixing them.

**Comment by namangoel1** [comment]
Also, please use 'em's in media queries instead of pixels, and indent using 4 spaces.

**Comment by wongalvis** [comment]
@namangoel1  Noted, will do :)

**Pull request merged**
