### PR TITLE
Added photo and information

### PR DESCRIPTION
**Pull request by domsaun**

### CODE REVIEW

**Comment by roonyh** [comment]
Thanks! This looks fine except for the small indentation error. Lets just neglect it. Shall we merge this @namangoel1?

**Comment by namangoel1** [comment]
Great, this is very better! I'll fix and merge.

**Comment by domsaun** [comment]
Yay! Thank you!

**Comment by namangoel1** [comment]
All done! Great work @domsaun

@RoonyH could you somehow close https://github.com/fossasia/fossasia.github.io/pull/181?

**Comment by domsaun** [comment]
Great! Thanks a lot.

**Comment by roonyh** [comment]
@namangoel1 closed! 

@domsaun Did you claim a task for this? You can submit a link to this pull request and mark it as completed and give me a link so that I can close it.

**Comment by domsaun** [comment]
I did and what exactly do you mean by that? (RE submitting a link to the pull request) 

```
 On Friday, January 2, 2015 3:59 AM, Aruna Herath <notifications@github.com> wrote:
```

 @namangoel1 closed! @domsaun Did you claim a task for this? You can submit a link to this pull request and mark it as completed and give me a link so that I can close it.—

**Pull request merged**
