### PR TITLE
Added rule in .jscs.json

### PR DESCRIPTION
**Pull request by wongalvis**
Added "validateParameterSeparator": ","
Enforce validateParameterSeparator to accept only "," (function parameters are immediately followed by a comma) by adding suitable entry in the .jscs.json.

### CODE REVIEW

**Comment by roonyh** [comment]
Thanks. There's a task for this work and if I get a pull request for that I will accept it instead. Claim it if you are free. I think its better if you work after claiming the task to avoid conflicts until the contest ends. After the competition you are free to work as you please and I will be delighted to see your contributions :smile:

**Comment by roonyh** [comment]
please see my comments in https://github.com/fossasia/fossasia.github.io/pull/214
I don't think jscs currently read our configurations in the .jscs.json file. Could you please run those linters locally and verify if configuration on .jscs.json actually works?

**Comment by roonyh** [comment]
Ask me in #fossasia if you need help.

**Comment by namangoel1** [comment]
Shouldn't we keep it to be ", " @RoonyH @pwmvx1289 ? Only a "," looks pretty close and ugly, imo. 

Btw, seems like this https://github.com/pwmvx1289/fossasia.github.io/commit/dd7cd7c3237712a5572dbbe494e0586976d42f22 breaks the current travis configuration by reverting to an older version? 

The changes you make in 5e5d760 are already in the repo - https://github.com/fossasia/fossasia.github.io/blob/master/javascripts/main.js. Please merge properly.

**Comment by namangoel1** [comment]
Also, why is `validateIndentation` 2 here? https://github.com/pwmvx1289/fossasia.github.io/commit/ea33dd2a4c754db6a106770e011905875a9b129d shouldn't this be 4?

(Ignore this, clarified with @RoonyH)

**Comment by namangoel1** [comment]
Please rename`.jscs.json` to `.jscsrc`. I discussed with @RoonyH and it is more standard. Thanks! 

You'll also need to change your separator to be `", "` instead of `","`.

**Comment by namangoel1** [comment]
Please separate your rules to .jscsrc, thanks.

**Comment by roonyh** [comment]
@namangoel1 i am talking to @pwmvx1289 in IRC, and will work on this PR with him.

**Pull request closed without merging**
