### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by domsaun**
Updated index.html, added credentials and photo

### CODE REVIEW

**Comment by samarsault** [comment]
Hey @domsaun I guess your pull doesn't have your image. Go through the instructions here at https://github.com/fossasia/fossasia.github.io/blob/master/README.md and try again.

**Comment by namangoel1** [comment]
@domsaun Your changes can't be merged right now since it seems you haven't uploaded your image. As @samarjeet27 said, please add one, I'll be happy to merge then :)

**Comment by domsaun** [comment]
Thanks for the reply and advice. I did try to upload a picture using the instructions, but it didn't work. I'm not exactly clear on how to go about doing it, with regards to the command prompt vs. the actual website 

---

**Comment by roonyh** [comment]
Hi, the instructions are changed a bit now. https://github.com/fossasia/fossasia.github.io#adding-images. Basically you can add the image by only writting few json lines. No need to code html.

Adding images is not that hard :smile: Its like committing any other file using git. You can commit the image file the same way you add the changes to index.html file.

But as I said, the workflow is changed a bit. Read the instructions carefully. Ask here or in our IRC channel `#fossasia` if you need more help.

**Comment by domsaun** [comment]
I'm trying to install mocha, but it isnt working.  

```
 On Friday, January 2, 2015 12:29 AM, Aruna Herath <notifications@github.com> wrote:
```

 Hi, the instructions are changed a bit now. https://github.com/fossasia/fossasia.github.io#adding-images. Basically you can add the image by only writting few json lines. No need to code html.Adding images is not that hard  Its like committing any other file using git. You can commit the image file the same way you add the changes to index.html file.But as I said, the workflow is changed a bit. Read the instructions carefully. Ask here or in our IRC channel #fossasia if you need more help.—

**Comment by roonyh** [comment]
Oh. Skip that step. Follow others.

**Comment by domsaun** [comment]
when I fork the repository, the _data folder doesnt show up. Is this a problem? 

```
 On Friday, January 2, 2015 12:53 AM, Aruna Herath <notifications@github.com> wrote:
```

 Oh. Skip that step. Follow others.—

**Comment by roonyh** [comment]
That is a problem. And is impossible :smile: 

Maybe you are clonning your own fork. The less complicated solution would be deleting your fork and forking again. https://help.github.com/articles/deleting-a-repository/

**Comment by domsaun** [comment]
LOL, thanks a lot, I just realised that I was doing exactly that. I'll try again :) 

```
 On Friday, January 2, 2015 1:08 AM, Aruna Herath <notifications@github.com> wrote:
```

 That is a problem. And is impossible  Maybe you are clonning your own fork. The less complicated solution would be deleting your fork and forking again. https://help.github.com/articles/deleting-a-repository/—

**Comment by domsaun** [comment]
after I add my credentials to the file, do I click Commit changes or continue with the command prompt instructions? 

```
 On Friday, January 2, 2015 1:16 AM, Stewart Saunders <dom.saun@yahoo.com> wrote:
```

 LOL, thanks a lot, I just realised that I was doing exactly that. I'll try again :) 

```
 On Friday, January 2, 2015 1:08 AM, Aruna Herath <notifications@github.com> wrote:
```

 That is a problem. And is impossible  Maybe you are clonning your own fork. The less complicated solution would be deleting your fork and forking again. https://help.github.com/articles/deleting-a-repository/—

**Comment by roonyh** [comment]
Add your image to the images folder too. Remember it should be an square in the shape. And then commit changes. No need to follow command line instructions if you are using the desktop client.

**Comment by domsaun** [comment]
when it says open with an editor, what does it mean? because I edited it on the actual website 

```
 On Friday, January 2, 2015 1:47 AM, Aruna Herath <notifications@github.com> wrote:
```

 Add your image to the images folder too. Remember it should be an square in the shape. And then commit changes. No need to follow command line instructions if you are using the desktop client.—

**Comment by roonyh** [comment]
Thats fine. As long as you commit the image file.

**Comment by domsaun** [comment]
oh, I think that's where my problem lies. I added my photo to the folder, but Im not sure how to commit the change.  

```
 On Friday, January 2, 2015 1:53 AM, Aruna Herath <notifications@github.com> wrote:
```

 Thats fine. As long as you commit the image file.—

**Comment by namangoel1** [comment]
On the command line, enter `git add . --a`. Then type `git status` to see a list of files you've modified. You should see the image on the list and _data/students.json there.

**Comment by roonyh** [comment]
I think @domsaun is using a github desktop client. If thats the case checkout https://help.github.com/articles/synchronizing-repositories/

**Comment by domsaun** [comment]
I'm actually kinda using both. The name of my file is Dominic.jpg, so should the command be git add Dominic.jpg --a ? 

```
 On Friday, January 2, 2015 2:04 AM, Aruna Herath <notifications@github.com> wrote:
```

 I think @domsaun is using a github desktop client. If thats the case checkout https://help.github.com/articles/synchronizing-repositories/—

**Comment by roonyh** [comment]
What is the output of `git status`?
`git add Dominic.jpg` should be fine. Follow the relevant instructions. I think this will be much easier if you closely follow those using git in the command line. Instead of using both.

**Comment by domsaun** [comment]
new file: images/students/Dominic.jpg

**Comment by namangoel1** [comment]
@domsaun Perfect. Have you made changes to _data/student.json?

**Comment by domsaun** [comment]
Yeah, but I used the editor on the website and clicked the Commit Changes button. I didnt know how to use command line to do this part. 

```
 On Friday, January 2, 2015 2:25 AM, namangoel1 <notifications@github.com> wrote:
```

 @domsaun Perfect. Have you made changes to _data/student.json?—

**Comment by roonyh** [comment]
I thought the given instructions were clear. What was troubling you? This
will be a lot less messy if you followed the instructions closely. It will
help your future contributions as well. Please start again from forking and
follow the instructions. Sadly this would mean deleting your fork again.

On Fri, Jan 2, 2015 at 1:01 PM, domsaun notifications@github.com wrote:

> Yeah, but I used the editor on the website and clicked the Commit Changes
> button. I didnt know how to use command line to do this part.
> 
> On Friday, January 2, 2015 2:25 AM, namangoel1 notifications@github.com
> wrote:
> 
> @domsaun Perfect. Have you made changes to _data/student.json?—
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fossasia/fossasia.github.io/pull/169#issuecomment-68512059
> .

## 

Regards,
Aruna Herath

**Comment by domsaun** [comment]
ok, then how do I make changes to the _data file without using the website?

**Comment by namangoel1** [comment]
What do you mean, 'without using the website'? Open the `_data/students.json` file in a text editor, copy paste code from a previous student, edit it.

**Comment by roonyh** [comment]
Have you cloned the project? After step 3 every file should be saved in
your machine. In your disk. Those files can be edited just like any other
file. Just open them in a text editor. Like notepad, gedit, sublime.

On Fri, Jan 2, 2015 at 1:16 PM, namangoel1 notifications@github.com wrote:

> What do you mean, 'without using the website'? Open the
> _data/students.json file in a text editor, copy paste code from a
> previous student, edit it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fossasia/fossasia.github.io/pull/169#issuecomment-68512431
> .

## 

Regards,
Aruna Herath

**Comment by domsaun** [comment]
I tried that yesterday and didnt see any changes. I'll try that again using notepad++ 

```
 On Friday, January 2, 2015 2:47 AM, namangoel1 <notifications@github.com> wrote:
```

 What do you mean, 'without using the website'? Open the _data/students.json file in a text editor, copy paste code from a previous student, edit it.—

**Comment by domsaun** [comment]
I did it. It worked with notepad++.  when I did git status, in red writing it said modified: _data/students.json and the same thing came up for the picture 

```
 On Friday, January 2, 2015 2:48 AM, Stewart Saunders <dom.saun@yahoo.com> wrote:
```

 I tried that yesterday and didnt see any changes. I'll try that again using notepad++ 

```
 On Friday, January 2, 2015 2:47 AM, namangoel1 <notifications@github.com> wrote:
```

 What do you mean, 'without using the website'? Open the _data/students.json file in a text editor, copy paste code from a previous student, edit it.—

**Comment by roonyh** [comment]
Great!! continue the rest of the steps and submit a pull request.

On Fri, Jan 2, 2015 at 1:44 PM, domsaun notifications@github.com wrote:

> I did it. It worked with notepad++.  when I did git status, in red writing
> it said modified: _data/students.json and the same thing came up for the
> picture
> 
> On Friday, January 2, 2015 2:48 AM, Stewart Saunders dom.saun@yahoo.com
> wrote:
> 
> I tried that yesterday and didnt see any changes. I'll try that again
> using notepad++
> 
> On Friday, January 2, 2015 2:47 AM, namangoel1 notifications@github.com
> wrote:
> 
> What do you mean, 'without using the website'? Open the
> _data/students.json file in a text editor, copy paste code from a previous
> student, edit it.—
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fossasia/fossasia.github.io/pull/169#issuecomment-68513062
> .

## 

Regards,
Aruna Herath

**Comment by domsaun** [comment]
I just submitted the pull request 

```
 On Friday, January 2, 2015 3:15 AM, Aruna Herath <notifications@github.com> wrote:
```

 Great!! continue the rest of the steps and submit a pull request.

On Fri, Jan 2, 2015 at 1:44 PM, domsaun notifications@github.com wrote:

> I did it. It worked with notepad++. when I did git status, in red writing
> it said modified: _data/students.json and the same thing came up for the
> picture
> 
> On Friday, January 2, 2015 2:48 AM, Stewart Saunders dom.saun@yahoo.com
> wrote:
> 
> I tried that yesterday and didnt see any changes. I'll try that again
> using notepad++
> 
> On Friday, January 2, 2015 2:47 AM, namangoel1 notifications@github.com
> wrote:
> 
> What do you mean, 'without using the website'? Open the
> _data/students.json file in a text editor, copy paste code from a previous
> student, edit it.—
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fossasia/fossasia.github.io/pull/169#issuecomment-68513062
> .

## 

Regards,
Aruna Herath—

**Comment by namangoel1** [comment]
@RoonyH can you close this? Thanks!

**Comment by roonyh** [comment]
merged #182

**Pull request closed without merging**
