### PR TITLE
Fixing visible issues on the site

### PR DESCRIPTION
**Pull request by namangoel1**
As per Mario on https://www.google-melange.com/gci/task/view/google/gci2014/5847951788212224

### CODE REVIEW

**Comment by namangoel1** [comment]
Hey @RoonyH @mariobehling, if you could have a look please? I have fixed all aesthetic problems since my last pull request. This and the last pull request complete 2 tasks so I'm a bit anxious to have them merged. Thank you!

**Comment by namanyayg** [comment]
@RoonyH @mariobehling I'd appreciate a reply. If there's anything to fix still, please do tell me.

**Comment by namangoel1** [comment]
@mariobehling @RoonyH Here I've fixed all the visible issues I found on the site. The site works perfectly on my local host, and can be automatically merged.

**Comment by mariobehling** [comment]
Could you check, if you could center the photostream, please? Thank you.

**Comment by namangoel1** [comment]
@mariobehling Seems like it is centered? http://i.imgur.com/3GGhVTe.jpg Am I missing something? Do you find something else on your system? May I know your operating system and web browser? Thanks!

**Pull request merged**
