### PR TITLE
Another commit with many small fixes [Urgent]

### PR DESCRIPTION
**Pull request by namangoel1**
Lots of small fixes, read through the detailed commit messages ;) 

It seems some of my changes from last time were overwritten. Can this be merged first so that any conflicts are chosen from this request rather than the other outdated ones? I'll be happy to fix conflicts if it is possible.

### CODE REVIEW

**Comment by namangoel1** [comment]
@RoonyH @mariobehling please have a look?

**Comment by namangoel1** [comment]
Completed [my task](https://www.google-melange.com/gci/task/view/google/gci2014/6458624197001216) with [this commit](https://github.com/namangoel1/fossasia.github.io/commit/42e095e5c3c480a4bd301a55c9af734d96aa761c).

**Comment by namangoel1** [comment]
Completed [task](http://www.google-melange.com/gci/task/view/google/gci2014/5892066202615808) with 394f1c2

**Comment by namangoel1** [comment]
Added animations again as per #55

**Comment by roonyh** [comment]
please also keep contribution details on the README.md file since its important that they appear on the projects home page. We can maybe add a wiki page later. and maybe instead of adding a new commit you can delete the old commit. do this and we can your much more valuble work in!

**Comment by namangoel1** [comment]
@RoonyH Which old commit?

**Comment by namangoel1** [comment]
@RoonyH All done :smile:

**Pull request merged**
