### PR TITLE
Improving Fossasia.github.io

### PR DESCRIPTION
**Pull request by mbelchev**
Improved Fossasia website with bootstrap and added all new students.

This is for my Google code-in task: http://www.google-melange.com/gci/task/view/google/gci2014/5573416824340480

### CODE REVIEW

**Comment by roonyh** [comment]
@mbelchev Hi welcome!
It seems your master branch is not up to date. We have added some commits this morning. Can you please pull this changes in and rebase your work on top of it? If you need help doing this please comment here. 
Thanks!

**Comment by mbelchev** [comment]
@RoonyH Hello!
Yesterday i remake the whole design of the site by using bootstrap. The structure is different. I was following the Google code-in task. If you mean to add the new menu, which is on top of the website i can do it.
However, what do you mean by "your master branch is not up to date"? I fork your repository, which means all things are up to date, also i pull it before the update.
Thank you!

**Comment by roonyh** [comment]
@mbelchev Oh right. My mistake.

Its just that this commit deletes some files that we need and undos some of the work by other students. For example the nice animation that you see when you mouse over images is gone.

This is because as you said some changes have been added to the site after you started working. This is a problem we face very often when we work in teams.

I am sorry for asking this but how hard do you think it is for you to redo what you did earlier again in this new state? I feel it will be easier for you to do that than untangling this code. Its nobody's fault and such a common thing that happens.

**Comment by roonyh** [comment]
@mbelchev you can do `git reset --hard HEAD^` to completely undo your work. And then can you add the nice animation that you put on images again and make a pull request. you will have to force push to your branch using `git push -f`. I am sorry about this but I don't know any other easier way to get in your nice work in.

**Comment by mbelchev** [comment]
@RoonyH Its OK. I think it is easy for fixing. Will try to do it and will pull new request. Thanks for helping me!

**Comment by roonyh** [comment]
Let me know if you run into problems with git. And if you like, you can submit whatever work you have done so far and then continue to work on.

**Comment by mbelchev** [comment]
I am ready with the project. Also i make it responsive but i dont have access to my computer right now to sent it. Will pull request later today.

**Comment by roonyh** [comment]
awsome!! eagerly waiting..

**Comment by roonyh** [comment]
closing since #36 is merged.

**Pull request closed without merging**
