### PR TITLE
Fixed google code-in link, the one at the footer(it was broken)

### PR DESCRIPTION
**Pull request by PolBaladas**
The link at the footer of the page to google code-in website was broken, just changed the link in index.html

### CODE REVIEW

**Comment by Legoben** [comment]
Ah, this is my bad. Thanks for fixing it.

**Comment by roonyh** [comment]
Thanks! Its more my fault for merging without checking.

**Comment by roonyh** [comment]
@PolBaladas Btw, I can see that you have removed some unnecessary white spaces. Maybe your editor did it. This is a good thing. Thanks! But its better if you can do that in a separate commit, to keep commits clean. :smile:

**Comment by PolBaladas** [comment]
No worries, I found and fixed it. That's collaboration isn't it?
About whitespaces, I think that it was the editor probably.

Thanks, great working with this team!

**Pull request merged**
