### PR TITLE
Miscellaneous updates

### PR DESCRIPTION
**Pull request by Legoben**
Added myself
Student links, mentor links, and contributor links all open in new tabs
Git links now lead to profiles instead of API
Hyperlinked GCI in footer
Used beautify to reformat the HTML and JavaScript

### CODE REVIEW

**Comment by roonyh** [comment]
Thank you very much! These are all very welcome changes. Can you link me the code-in task relevant to this work?

**Comment by Legoben** [comment]
Currently waiting on a different task to be reviewed, but I plan to eventually claim this one: http://www.google-melange.com/gci/task/view/google/gci2014/6670192289513472

**Comment by Legoben** [comment]
I think its because of beautifying it. It went through and redid all of the indentations in index.html and main.js, so it thinks I replaced every one of those lines.

**Comment by roonyh** [comment]
But it re-adds images and fonts too. Anyway don't worry about it.

**Comment by Legoben** [comment]
Oh. In one place it readded all of the files, but in another it says I only changed four of them. I don't know why it did that.

**Comment by roonyh** [comment]
Yeah its just git. It does no harm so I'll merge this. Thanks!

**Comment by roonyh** [comment]
Please give me a link to the task you are waiting for a review if its from fossasia.

**Pull request merged**
