### PR TITLE
Adding Toshita Barve to students.

### PR DESCRIPTION
**Pull request by toshitabarve**
Added myself to GCI students.

### CODE REVIEW

**Comment by namangoel1** [comment]
@toshitabarve I've added comments to the file, please see and fix.

**Comment by namangoel1** [comment]
@toshitabarve Great, thanks! It would be great if you're able to fix the indentation as well.

To check the site, you can do two things:
1. Create a branch 'ghpages' and upload it. Then you can see the site at toshitabarve.github.io/fossasia.github.io. [Here's a quick guide](http://stackoverflow.com/questions/5807459/github-mirroring-gh-pages-to-master)
2. Follow [this guide](http://codein.namanyayg.com/blog/ghpages/) to set up a local environment.

The latter is a bit difficult to set up, but definitely more useful for testing.

**Comment by namangoel1** [comment]
Great, thanks! This looks perfect, just one last request. It's better to have one commit instead of 3 that work on the same files, so can you squash your last commits? Here's a [short guide](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git/5201642#5201642). 

Running these two lines should work:

```
git reset --soft HEAD~3 &&
git commit
```

Thank you very much for the great work @toshitabarve ! :smile:

**Comment by toshitabarve** [comment]
I am using GitHub Windows (https://windows.github.com) and I am not sure where I am supposed to run these commands.

**Comment by namangoel1** [comment]
@toshitabarve Understood, don't worry about this then. I'll fix this. Let me know if you have any problems running a demo site.  Thanks!

**Comment by roonyh** [comment]
Please merge if work is ok. Don't worry much about commits. :) and if you
try to fix the commits, be aware of the authorship of commit. The student
should be credited for their work.

**Comment by namangoel1** [comment]
@RoonyH She is :) Can you close this manually? Seems like Git didn't detect due to me rebasing.

**Comment by roonyh** [comment]
I am sorry, I don't follow. Close this? Can't it be merged? Commits look fine to me. I am all tired sleepy and on phone. Merge if code look fine to you.

**Comment by namangoel1** [comment]
@RoonyH I've merged by rebasing, but it seems that Github cannot identify that the pull request has been merged. I'd like you to close it manually, since the pull request _has_ been merged.

**Comment by roonyh** [comment]
Ah. Got it.

**Pull request closed without merging**
