### PR TITLE
Added mail form

### PR DESCRIPTION
**Pull request by amramadan**

### CODE REVIEW

**Comment by roonyh** [comment]
Hey! Thanks for this work!

I see that you are adding some css to the stylesheet. Can you add them on a seperate section.

The text in the style sheet are in different sections for eg:

/\* ==========================================================================
   =FOOTER
   ========================================================================== */

according to what part or thing in the page they are relevant to. Its easier for read and maintaining. Please add a section named "subscribe email" and add those css there.

**Comment by roonyh** [comment]
And the html regarding this should too be in its own section. Check the html file for lines like
`<section class="section--about page-section" id="map">` that open new sections. Please keep that pattern and add your new html code inside a new section.

**Comment by amramadan** [comment]
So u want me to add the section for e-mail in css but I dont understand the second comment

**Comment by roonyh** [comment]
Have a look at following lines
https://github.com/amroto/fossasia.github.io/blob/master/index.html#L94
https://github.com/amroto/fossasia.github.io/blob/master/index.html#L100
https://github.com/amroto/fossasia.github.io/blob/master/index.html#L218

They contain `<section>` tags. They mark separate sections of the page like the map, mentors, studens etc. So Its better if you put the new html you added, enclosed inside a `<section>` tag. Is that clear?

**Comment by amramadan** [comment]
Yes, thank you

**Comment by amramadan** [comment]
Waiting for review !

**Pull request merged**
