### PR TITLE
A fresh theme

### PR DESCRIPTION
**Pull request by namangoel1**
Completely updated the site, creating a new design from scratched. Added images of mentors and students, with two placeholder slots for those who wish to complete the other tasks.

### CODE REVIEW

**Comment by namangoel1** [comment]
Preview here: http://codein.namanyayg.com/fossasia/site/

**Comment by kokoye2007** [comment]
gr8! job.

cool and clean

On Fri, Dec 5, 2014 at 2:33 PM, namangoel1 notifications@github.com wrote:

> Preview here: http://codein.namanyayg.com/fossasia/site/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fossasia/fossasia.github.io/pull/1#issuecomment-65758364
> .

## 

_Ko Ko Ye`_

+95 973147907
+95 94500 22022

kokoye2007@gmail.com
kokoye2007@ubuntu.com

skype: kokoye2007
jit.si: kokoye2007

http://ubuntu-mm.net
http://wiki.ubuntu.com/kokoye2007
http://wiki.ubuntu.com/MyanmarTeam
http://loco.ubuntu.com/teams/ubuntu-mm

**Comment by namangoel1** [comment]
@kokoye2007 Thanks! Any changes you'd like to see?

**Comment by roonyh** [comment]
@namangoel1 Overall work is really good. However your work on git could have been better. For example commit messages should be more descriptive of the work they contain. Just two words as a commit message is really very less useful. When working on a collaborative project you must make sure that your work can be worked on later by other people. A good commit message helps others a lot to understand what happens inside the commit. Just google "What is a good commit message". You don't have to follow every instruction that would come up from this search. But try to write useful commit messages.

Another less important advice might be to have cleaner commits. For example README.md file is changed by you across 3 commits where it really logically could have been done in one commit itself. It really takes time to practice this so don't worry about it. But have a look at _git reset_ and _git interactive rebase_ if you have time which can help you to achieve this.

**Comment by namangoel1** [comment]
@RoonyH I understand and will keep this in mind for the future commits. Getting this set-up was a bit hacky I agree, I ported compiled files from Gulp into the repo and thus have messy commits.

**Comment by roonyh** [comment]
@namangoel1 I think you should still give those commits better commit messages. And get rid of the third commit and squash it into the second. Use git interactive rebase. Its a nice tool to know about. You can always clone again from here if you mess up :) give it a try!

**Comment by namangoel1** [comment]
@RoonyH Can't seem to figure out how to use git interactive rebase.

If I do: `git rebase -i origin/master` simply shows `noop` in the vim shell. Not sure what I'm doing wrong. Could you help out through IRC or something if it is okay?

**Comment by roonyh** [comment]
@namanyay1 I am travelling right now, so wouldnt be able to join IRC. Try git rebase -i. Try to search about it.

**Comment by namangoel1** [comment]
Thanks for merging. I tried git rebase -i and it always shows me 'noop'. Tried it on the origin (which failed), origin/master (noop) and master (noop) branches. I am not sure why. Shall I create another pull request for demonstration?

**Comment by roonyh** [comment]
@namanyay1 thanks much! Learn about git rebasing when you have time. Lets get this nice work of yours in for now. Thanks again!

**Comment by namangoel1** [comment]
@RoonyH Great, thank you! Will do.

**Pull request merged**
