### PR TITLE
Added favicon and fixed URLs in header

### PR DESCRIPTION
**Pull request by Legoben**
Added Favicon
Fixed added onclick animation to photo stream link
Gave photo stream and Twitter feed separate IDs
Fixed sudden jumping when using automatic scrolling.

### CODE REVIEW

**Comment by roonyh** [comment]
Thanks much!

**Comment by roonyh** [comment]
@Legoben Hi! Can you see the favicon in http://fossasia.github.io/? It doesn't show up in any of my browsers. I tried clearing the cache and private browsing. Its weird because it shows up when I run locally and even here: http://roonyh.github.io/fossasia.github.io/

**Comment by Legoben** [comment]
@RoonyH I am not able to, I thought it was just me (because it does show up locally). I don't have any idea why it is doing this. It looks like the browser isn't even requesting it in Chrome: Network Tools

However, when viewing it in FireFox (first time I've opened the site with it) it appears fine.
Site in FireFox

I'm stumped. It looks like it is some sort of caching issue, but I don't know why clearing the cache didn't 
fix it.

**Comment by roonyh** [comment]
Ok. Now it shows up in chrome! Some weird caching issue it seems. Thanks for checking and no need to worry now. :)

**Pull request merged**
