### PR TITLE
Added "Thank you for contributing" in Arabic

### PR DESCRIPTION
**Pull request by tiatmed**
Added "Thank you for contributing" in Arabic to the index.html file

### CODE REVIEW

**Comment by amramadan** [comment]
please fix to:
شكرا لكم على المساهمة
and not:
شكرا لك على المساهمة

**Comment by amramadan** [comment]
and also make it:
!شكرا لكم للمساهمة
I assure you this is much better google translates arabic grammar incorrectly I am an Egyptian so I am sure it is correct

**Comment by tiatmed** [comment]
Okay, I went ahead and made the changes you suggested.

**Comment by roonyh** [comment]
Thanks much both of you! @amroto does this look right?

@tiatmed Could you please rebase your pull request? http://stackoverflow.com/questions/17182624/contributing-to-project-on-github-how-to-rebase-my-pull-request-on-top-of-mast

**Comment by tradzik** [comment]
It seems this is added to `index.html` already. Closing...

**Pull request closed without merging**
