### PR TITLE
DeRaedt

### PR DESCRIPTION
**Pull request by gderaedt**
I hope I did it correctly this time! Thanks.

### CODE REVIEW

**Comment by roonyh** [comment]
Hi @gderaedt! You are getting there :smile: 

@fossasia/fossasia-gci-students Can you guys please help out @gderaedt to add her picture to the site?

**Comment by chaconne7** [comment]
@gderaedt - you're getting closer! Your code to add your picture to the website is stuck down in the footer, though. (You can tell this because it is between the footer tags.) You need it to be in the "Students" section, which starts at line 121 in the current index.html file. Each individual student's picture and info starts with `<div class = "sympl onethird">` and ends with a closing `</div>` tag. You can copy and paste one of these blocks and substitute the name and social media/Github links with your own information. 

I'm not sure how familiar you are with HTML, but it's really helpful to look at the indentation and see which opening tags line up with which closing tags. 

Does this help at all? HTML can be confusing, but there are some really helpful free tutorials online, like CodeAcademy.

**Comment by gderaedt** [comment]
Thank you :) That helps a lot! I am actually new to all forms of coding, but I can use HTML and CSS some.

**Comment by chaconne7** [comment]
Great! Oh, just remembered one other tip - if you open the index.html file with your web browser, you can refresh it as you make changes and save them in your text editor, and see what the webpage looks like. Then if there are any glaring errors, you'll notice them.

I'm no expert coder, either, but let me know if you need any more help with the HTML/CSS stuff. :-)

**Comment by gderaedt** [comment]
@chaconne7 I just updated the index!

**Comment by gderaedt** [comment]
Ok, thank you very much your information and tips helped a lot. I hoped I fixed it this time.

**Pull request closed without merging**
