### PR TITLE
Integrating scss-lint through Gulp with Travis CI

### PR DESCRIPTION
**Pull request by namangoel1**
Once I'd done the integration, had to fix many, many errors across various files. Hence 11 files changed.

### CODE REVIEW

**Comment by roonyh** [comment]
Excellent! But are you changing libraries from other parties? https://github.com/namangoel1/fossasia.github.io/blob/gh-pages/stylesheets/partials/_animate.scss

**Comment by namangoel1** [comment]
@RoonyH yes, but that's only to change the indentation and change 0<unit> to simply be 0. scss-lint was giving warnings. It doesn't matter in validation or execution, though.

**Comment by roonyh** [comment]
Is there a way to exclude external code from linting? and maybe have them in a separate directory too.

**Comment by namangoel1** [comment]
Sure @RoonyH, can be done. I don't see why, though - I have fixed all errors in this commit, most were related to indenting anyway. If you see [Travis' output](https://travis-ci.org/fossasia/fossasia.github.io/jobs/45770590), you'll find that there are no errors or warning for any of the included files.

I have excluded _animate.scss because there still were some warnings there (SCSS lint does not like names in camelcase and forces dash-separation instead). 

You on IRC right now?

**Comment by roonyh** [comment]
I see the travis build and know that there are no problems :) But I don't like messing with external code. say there is a new update to this file. and we want to get it. There will be merge conflicts. External code is external code :) From experience I know that they are best kept that way. I am on IRC.

**Pull request merged**
