### PR TITLE
Added photo and information

### PR DESCRIPTION
**Pull request by domsaun**
Photo added and credentials updated

### CODE REVIEW

**Comment by namangoel1** [comment]
Doesn't seem that you added your information, @domsaun. See https://github.com/domsaun/fossasia.github.io/commit/3cf620983710e61f0df0ab686ca42ee1a7331646. It only shows your photo.

**Comment by domsaun** [comment]
ok, I'll try it again

**Comment by domsaun** [comment]
What am I suppose to upload on the Google Code In site for my mentor to review? 

```
 On Friday, January 2, 2015 3:57 AM, Aruna Herath <notifications@github.com> wrote:
```

 Closed #181.—

**Comment by namangoel1** [comment]
@domsaun The URL of #182 will do.

**Comment by domsaun** [comment]
Thanks much. I just uploaded it.  

```
 On Friday, January 2, 2015 4:05 AM, namangoel1 <notifications@github.com> wrote:
```

 @domsaun The URL of #182 will do.—

**Pull request closed without merging**
