### PR TITLE
Adding Picture

### PR DESCRIPTION
**Pull request by RzSh33**
Adding my picture to students folder.

### CODE REVIEW

**Comment by samarsault** [comment]
hey @RzSh33 , you need to edit the _data/students.json for your picture to appear. See https://github.com/fossasia/fossasia.github.io/wiki/Installing-GitHub-And-Adding-Images

**Comment by RzSh33** [comment]
Hi,
How do I know if my pull request has been completed?
Thanks

**Comment by namangoel1** [comment]
@RzSh33 you just closed this pull request, it cannot be merged now. Why did you do that?

The changes you made look great, you just are missing a comma after the } of 'social'. Please add that and create another pull request (since you've closed this one).

Thanks!

**Comment by RzSh33** [comment]
Sorry, Github noob here!

**Comment by namangoel1** [comment]
@RzSh33 This looks perfect, I'll merge as soon as travis passes. Thanks!

**Comment by namangoel1** [comment]
Oh wait, please remove the '@' from Twitter.

**Comment by RzSh33** [comment]
Okay I fixed it.

**Comment by RzSh33** [comment]
Are there other issues?

**Comment by namangoel1** [comment]
@RzSh33 Nope, perfect. Merged, it's now visible on the site. Thanks!

**Pull request merged**
