### PR TITLE
Changed links for one of the students, removed testing link

### PR DESCRIPTION
**Pull request by tradzik**
I've finished task for GCI. My image has been resized by somebody, I have changed one of the students link to better form and removed testing link. Please approve my task on Melange.

### CODE REVIEW

**Comment by roonyh** [comment]
@ty221 please give me a link to your task.

**Comment by tradzik** [comment]
http://www.google-melange.com/gci/task/view/google/gci2014/5559220615249920

Here you are :-) @RoonyH

**Comment by roonyh** [comment]
@ty221 Thanks for this work. Your task closed! I have asked the student whose image you fixed to fix it himself. Lets give him some time. And instead of removing the test link can you make it link fossasia gci homepage?

**Comment by tradzik** [comment]
Ok I'll so that in the second. I claimed new task. Can you assign it to me?

**Comment by roonyh** [comment]
Sure. If you can give me the link? And after claiming you can go ahead and work on it. We wouldnt remove your claim. :)

**Pull request closed without merging**
