### PR TITLE
Reworking layout and design of social icons in footer

### PR DESCRIPTION
**Pull request by namangoel1**

### CODE REVIEW

**Comment by namangoel1** [comment]
@RoonyH sorry for the messed up commits, seems like it can't auto merge. If you give the thumbs up, I'll merge on my end manually.

**Comment by namangoel1** [comment]
@RoonyH Sorry for the messed up commits, I'll merge manually if you give the thumbs up.

**Comment by roonyh** [comment]
What is going on with git though! I'd love to know why this is happening. Anyway looks good at http://namangoel1.github.io/fossasia.github.io/. Can you try one more time with git?

**Comment by namangoel1** [comment]
What shall I try @RoonyH? Not too certain.

**Comment by roonyh** [comment]
you can do get `reset --hard upstream/master` to make your branch exactly like the upstream master. This will loose your work though. and then `git cherry-pick 940b29f457a49ab331caee3df38ad519c5d8c406` to get those back.
I am not sure if your work can be recovered so back up first.

**Comment by roonyh** [comment]
im in #fossasia if you need help.

**Comment by namangoel1** [comment]
@RoonyH got it working!

**Comment by roonyh** [comment]
nice! did the reset cherry-pick thing?

**Comment by namangoel1** [comment]
Restored it manually from a backup after a hard reset

**Comment by roonyh** [comment]
hmm. cherry-picking might have done it. anyway glad you got it sorted.

**Pull request merged**
