### PR TITLE
Second Pull request

### PR DESCRIPTION
**Pull request by MarioScappini**
Look the thing that you will see almost no changes but the thing is that i made this task before(add the student and  tweeted) but i could upload my work, so i unclaimed it, and now im trying to see if i can upload the work that i did before

### CODE REVIEW

**Comment by MarioScappini** [comment]
the new commits are student photo and credentials and student info change

**Comment by namangoel1** [comment]
@MarioScappini Again, it seems you're working on an old version of the site. You do not have to edit the index.html file at all as per the new changes. If you're having difficulties, delete the repository and clone again.

**Comment by MarioScappini** [comment]
look i did it like 3 times same as in here says https://github.com/fossasia/fossasia.github.io/wiki/Installing-GitHub-And-Adding-Images and its doesnt working

**Comment by namangoel1** [comment]
@MarioScappini Do you see the "students.json" file in your "_data" folder? If not then you have an older version of the repo.

**Comment by MarioScappini** [comment]
here https://github.com/fossasia/fossasia.github.io/pull/241

**Pull request closed without merging**
