### PR TITLE
Updated mentor Aruna's picture

### PR DESCRIPTION
**Pull request by akshattripathi**

### CODE REVIEW

**Comment by roonyh** [comment]
Please add other contact details as well. http://en.gravatar.com/arunabherath

**Comment by akshattripathi** [comment]
Done. :)

**Comment by namangoel1** [comment]
@akshattripathi, you only need to include the username in all fields. G+ seems to have unnecessary '/u/0//u/0/+' characters in the beginning.

**Comment by roonyh** [comment]
thanks!

**Comment by roonyh** [comment]
ooops! didn't see @namangoel1's comments

**Comment by namangoel1** [comment]
@RoonyH No worries, I'll get in and fix myself. @akshattripathi please take care of this the next time.

**Comment by roonyh** [comment]
@namangoel1 thanks! lets wait for akshat. @akshattripathi can you please fix this asap.

**Comment by namangoel1** [comment]
Fixed in https://github.com/fossasia/fossasia.github.io/commit/8a482096d39e51baa90247790c3923b261d6b285, nevermind :P

**Comment by roonyh** [comment]
thanks! :)

On Fri, Jan 2, 2015 at 5:27 PM, namangoel1 notifications@github.com wrote:

> Fixed in 8a48209
> https://github.com/fossasia/fossasia.github.io/commit/8a482096d39e51baa90247790c3923b261d6b285,
> nevermind :P
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fossasia/fossasia.github.io/pull/183#issuecomment-68522180
> .

## 

Regards,
Aruna Herath

**Comment by akshattripathi** [comment]
Sorry for being late (only about 3 minutes!) I almost fixed it after I saw @namangoel1 's comment. Will it keep in mind the next time, I just saw other's link and I saw that '/u/0', so I thought that I should add it as well.

**Comment by namangoel1** [comment]
@akshattripathi Thanks for catching that! Turns out there's a problem with Hong Phuc's G+ link. Pushing a fix.

**Comment by akshattripathi** [comment]
:)

**Pull request merged**
