### PR TITLE
Added Youtube subscribe button

### PR DESCRIPTION
**Pull request by wongalvis**

### CODE REVIEW

**Comment by namangoel1** [comment]
Anywhere to see this, @pwmvx1289 ?

**Comment by wongalvis** [comment]
@RoonyH It can be viewed here http://pwmvx1289.github.io/fossasia.github.io/

**Comment by roonyh** [comment]
Its great that your github page is finally up! But I don't see the subscribe button there. In-fact most of the header content is missing. 
http://awesomescreenshot.com/07946735bd

**Comment by wongalvis** [comment]
@RoonyH It's fixed now.

**Comment by roonyh** [comment]
Content in the header still disappears at the page load.

**Comment by wongalvis** [comment]
@RoonyH After some review I think it is not advisable to implement the button based on current conditions, I will come up with some new and nice methods later.

**Comment by roonyh** [comment]
Sure.

**Pull request closed without merging**
