### PR TITLE
Added 'Thank you for contributing' in Japanese, Chinese, Vietnamese, Mongolian and Hebrew

### PR DESCRIPTION
**Pull request by tradzik**
:D

### CODE REVIEW

**Comment by mariobehling** [comment]
Hi, how did you translate those? Automatic Google translation is usually wrong.

**Comment by tradzik** [comment]
Using auto-translation from Yandex, Bing and Google and comparing and vice-versing.

**Comment by mariobehling** [comment]
These are beginner tasks. Did you claim them?

**Comment by tradzik** [comment]
I didn't and I won't claim them. I have exceed my limit of beginners tasks already :p

**Comment by mariobehling** [comment]
Ok, so, the goal of these task is to ensure a correct translation and to enable students to learn in a simple task to commit with git.

If we just want those sentences on the website, we can do it ourselves in a few minutes. It would be great, if you help help us to find students e.g. who speak Korean, to translate it and support those students to commit changes, so they learn about git. 

As I understand - you do not know those languages and cannot confirm that your translations are correct. Hence, I cannot accept this pull request.

**Comment by tradzik** [comment]
I can confirm that in 100%, but in 95% surely. I did many translations on different webpages. But ok... Let us leave this task for some other people. I will help them if they will need help

**Comment by mariobehling** [comment]
I think it is great, that you are really fast doing lots of tasks. Maybe as you understand how to contribute to projects now, you could try a bit more difficult tasks and maybe start contributing to Open Source projects. I think mentors would be impressed by that more.

**Comment by tradzik** [comment]
@mariobehling I am currently working with @eMBee on sup command line client and eMBee's idea list. I hope and think eMBee appericates my work :D I try to contribute to FOSSASIA and other open source projects best as I can, because I really this idea of FOSS and FOSSASIA. As you can see I have recently wrote script to collect attendats of 2010 FOSSASIA. Please give me opinion about my work. I hope you appericate my work. Regards and good night ;-)

**Pull request closed without merging**
