### PR TITLE
Adding animations

### PR DESCRIPTION
**Pull request by mbelchev**
I am ready with bouncing and also two more animations. This time i used the code from the repository and just added the effects.

Check it and if i have to do something more to complete this task. Thanks! :)

### CODE REVIEW

**Comment by roonyh** [comment]
Very nice! We can get this in!
Just curious, whats with deleting jquery and adding again :)
I'll merge this as soon as I am at a computer. Thank you very much!

**Comment by mbelchev** [comment]
Hm, i deleted it because you have already included jquery but i saw that later.

I marked my Google code-in task as complete. May you accept it after merging and reviewing to continue the competition. Also i have one question. Now if i want to improve fossasia.github.io with another idea(from your tasks) and pick another task in google-melange am i able to work on it or i have already did something for you and i have to find another task? 
Thank you!

**Comment by roonyh** [comment]
of course you can pick whatever task you like :smile:

**Comment by roonyh** [comment]
Oh I forgot. Can you please put your image and links with other students if you don't mind?

**Pull request merged**
