### PR TITLE
Fix error in mentors.json

### PR DESCRIPTION
**Pull request by samarsault**

### CODE REVIEW

**Comment by namanyayg** [comment]
Where do you see an error, @samarjeet27 ?

**Comment by namangoel1** [comment]
Where do you see an error, @samarjeet27 ? This is compiled by Github properly... Merged for aesthetic reasons.

**Comment by samarsault** [comment]
See last line, json files don't have a ';' after array, that's for programming languages

**Comment by samarsault** [comment]
@namangoel1 students.json doesn't have it, just got this error while parsing the JSON so thought this would be helpful

**Comment by namangoel1** [comment]
@samarjeet27 Fair enough, thanks!

**Comment by roonyh** [comment]
Github has been kind to us by parsing it without error. This would have given an error on many parsers since the specification does not allow it. This has more importance than aesthetics. :) Thanks for the catch @samarjeet27

**Comment by namangoel1** [comment]
Wasn't aware, TIL. Thanks @RoonyH and @samarjeet27

**Pull request merged**
