### PR TITLE
Improved the fonts and coloring

### PR DESCRIPTION
**Pull request by akshattripathi**
Made them better than earlier which makes the white text more readable on a grey background. Also, changed the fonts of the title, they look much better now,

### CODE REVIEW

**Comment by namanyayg** [comment]
Can you show a preview? You can use gh-pages on your fork to show one. I am not too sure of these changes, I do not like the font personally.

**Comment by namangoel1** [comment]
Can you show a preview? You can use gh-pages on your fork to show one. I am not too sure of these changes, I do not like the font personally.

**Comment by akshattripathi** [comment]
Sure: http://postimg.com/image/186000/capture-185166.jpg
Also, I was thinking of removing many of the animations (especially that wobble one). Too many animations look a lot clumsy. How do I do it?

**Comment by akshattripathi** [comment]
Also, will be possible to take that 'NEEDSREVIEW' status back? I just thought of a few more changes I can make...

**Comment by roonyh** [comment]
Thanks for your work! But Please don't make design changes like those without talking with others about them. There are people who like the current font and animations.

**Comment by namangoel1** [comment]
Akshat, what task are you on that requires you to make these changes? The mentors have discussed about removing animations before, and it was decided to not remove animations.

I personally don't like the product with the font - What do you think @RoonyH , @mariobehling ?

Feel free to keep pushing changes here, they will add to the pull request. There is no way I know to remove the 'needsreview' status back without a mentor.

**Comment by akshattripathi** [comment]
All right, will keep that in mind next time. And this was the task: https://www.google-melange.com/gci/task/view/google/gci2014/5236848808951808

**Comment by namangoel1** [comment]
@akshattripathi What you've changed there is the navigation bar for mobiles. If that is kept fixed, then content will be obscured due to the small height of mobile devices. Also changing the color only for mobiles will seem strange, it is better to keep a solid, flat color - both on mobiles and desktops.

**Comment by akshattripathi** [comment]
Okay, so should I do it for desktops as well or remove the change entirely? Also (a minor change), I have changed the selection color as well because most of the color on the site of the text is mainly red.

**Comment by namangoel1** [comment]
@akshattripathi In my opinion you should remove the change entirely. Wait for a mentor to pass the final decision, though.

Hmm, I used red for mentors and my thinking was that red goes for the fossasia brand. Again, I'll let a mentor make the call on this one, but I prefer red myself.

**Comment by akshattripathi** [comment]
:) All right, thanks.

**Comment by namangoel1** [comment]
@RoonyH What do you think?

**Comment by roonyh** [comment]
lets not mess with colors and fonts now. Akshat has been assigned other work for his task. @akshattripathi Thanks for your work and caring about the website :)

**Pull request closed without merging**
