### PR TITLE
Change number of columns to five in contributors section

### PR DESCRIPTION
**Pull request by meghprkh**
Part of task : http://www.google-melange.com/gci/task/view/google/gci2014/5792122582073344

I think that it works perfectly. Test it @ http://meghprkh.github.io/fossasia.github.io/#contributors

### CODE REVIEW

**Comment by meghprkh** [comment]
The first commit just updated my repo

**Comment by roonyh** [comment]
Contributor images look really bad on mobile devices. See attached. Can you please fix this. You'll increase the minimum width of contributor images for this. Thanks!
fossasia google code in 2014 15

**Comment by meghprkh** [comment]
What is your pixel resolution?

It works nicely in FF's responsive tool.

But does the menu work at all for it does not work in FF?

screenshot from 2014-12-24 10 24 29

**Comment by roonyh** [comment]
Try on a tablet size. eg: nexus 7. (600x960)

Btw your work so far is really good. We just need this small fix and it can go in! This should not be a hard fix. Try to add a css class for contributor images and set min width to something smaller than the current one.

**Comment by meghprkh** [comment]
What about having 3 instead of 5 colums in contributor section on medium screen devices?

This looks clean.

See http://meghprkh.github.io/fossasia.github.io/ in FF responsive mode or on your tab.

**Pull request merged**
