### PR TITLE
Fixed width of .social

### PR DESCRIPTION
**Pull request by wongalvis**

### CODE REVIEW

**Comment by namangoel1** [comment]
@pwmvx1289 Please do not use pixel widths. em widths are better, but still not recommended. Change the padding instead. On my 1920x1080 the section looks very empty. If you want to do _something_, I suggest that you remove the left padding and increase the right padding to be around 1-2em.

**Comment by namangoel1** [comment]
@RoonyH can we revert this? Please see my comment about pixel widths.

**Comment by wongalvis** [comment]
@namangoel1 It's @RoonyH 's suggestion to fix the rows in a 4-4 style. px width applies the style to all screen sizes

**Comment by roonyh** [comment]
i did not see @namangoel1 earlier comments. is it necessary everything in this div seems to static with px dimensions?

**Comment by namangoel1** [comment]
If a 4-4 layout is desired, it would be better to have a break after the 4th element in the CSS (something like `.social li:nth-child(5) { clear: left; }`) instead of assigning a [magic number](http://css-tricks.com/magic-numbers-in-css/) width.

**Comment by pwmvx1289** [comment]
@namangoel1 clear: left doesn't work in this case

**Comment by namangoel1** [comment]
@pwmvx1289 Understood. I see a few problems in this implementation (inline elements hold block elements, there is no point to use a list in this case, the distance between two adjacent social media icons is simply the one provided by the browser). I'm going to quickly work on something more semantic and create a pull request.

**Pull request merged**
