### PR TITLE
Added 'Thank you for contributing in Vietnamese

### PR DESCRIPTION
**Pull request by domsaun**

### CODE REVIEW

**Comment by roonyh** [comment]
Thanks! It is important that we have the correct translation rather than the simple Google or another machine's, possibly not 100% correct, translation. Do you speak Vietnamese? If not could you please get someone who does to confirm the correctness of this translation?

Also a rebase would be nice. http://stackoverflow.com/questions/17182624/contributing-to-project-on-github-how-to-rebase-my-pull-request-on-top-of-mast

**Comment by tradzik** [comment]
Closing, as we're not sure about correctness of translation + no reaction from author.

**Comment by hongquan** [comment]
I confirm that the translation is correct.

**Comment by tradzik** [comment]
@hongquan Thanks!

**Pull request merged**
