### PR TITLE
Fixed an error

### PR DESCRIPTION
**Pull request by akshattripathi**
It is an error as there are other text in inverted quotes which don't have to be changed; to be more clear, I added that the text after colon should be change which is the actual case.

### CODE REVIEW

**Comment by akshattripathi** [comment]
Why is it not an error?

**Comment by namangoel1** [comment]
Why do you have two pull requests with the exact same thing? #199 and #203 seem duplicates.

**Comment by akshattripathi** [comment]
I actually forgot to comment there! Sorry, I should've commented there rather making a new pull request.

**Comment by roonyh** [comment]
hmm seems like @akshattripathi deleted his fork after making #199. l'll close it.
@akshattripathi were you trying to [synch your fork](https://help.github.com/articles/syncing-a-fork/)

**Comment by roonyh** [comment]
aah one second late! its closed :)

**Comment by akshattripathi** [comment]
:D Okay, I wanna hear from you all, why is that line not an error?

**Comment by roonyh** [comment]
what do you mean not an error? I dont follow.

**Comment by namangoel1** [comment]
@akshattripathi The line you've changed is correct, I should've when I had fixed the code. I think this pull request should be merged.

**Comment by akshattripathi** [comment]
In the original article, it was written, "The text without inverted quotes should be your own credentials." However, there is no text without inverted quotes in the given code example, so, I changed it to "The text after the colon (`:`) should be your own credentials" When I put up the issue, it was not merged and... Thanks. :)

**Pull request merged**
