### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by akshattripathi**
For The Installation Process On Windows

### CODE REVIEW

**Comment by namangoel1** [comment]
Hey @askhattripathi, 
1. Please use Markdown numbering (instead of 1) 2), use 1. 1. - markdown autonumbers). 
2. Please fix the 'alt text' in images too - Either enter alternative text, or remove that part completely. 
3. See: https://github.com/akshattripathi/fossasia.github.io/tree/patch-1 for rendering problems. You can see that the code has some syntax highlighting problem, and has incorrect rendering. There is no 'link' or 'google plus' types in the code sample.
4. There is a typo in point 9.
5. It'd also be good if the images have text 'written', instead of scribbled using the brush tool.
6. It would be good if you could convert links to the format of [text](url) instead of simply url in points 1, 2, 4.

**Comment by akshattripathi** [comment]
1. I didn't use 1., 1. as the list is not continuous and Markdown was restarting my list every time an image was added.
2. Done.
3. The 'google plus', 'link' option isn't in any student's profile (as far as I've checked), it's for only mentors
4. Fixed.
5. I actually do not have the originals and it will take a lot of time to re-install and clone the repository, will it be fine if I leave it like this?
6. Done.

**Comment by akshattripathi** [comment]
Also, since 1., 1. isn't working, should I change it back to 1), 2)...?

**Comment by namangoel1** [comment]
Thanks for all the changes! 

1) Just saw that the syntax was causing formatting problems. Seems it's because this is multi-paragraph text, which cannot be avoided due to images. Feel free to change it back.

3) It is an option, but I'm not sure why no student has used it. Please add it, it has the exact same syntax as the mentors' one.

5) I cannot say. @RoonyH what do you think?

**Comment by roonyh** [comment]
lets bring this in for now. Thanks @akshattripathi

**Comment by akshattripathi** [comment]
No problem. :)

**Pull request merged**
