### PR TITLE
Adding Twitter feed

### PR DESCRIPTION
**Pull request by mbelchev**
Saw that as an option in improvement ideas. What do you think? 
Thank you!

### CODE REVIEW

**Comment by roonyh** [comment]
@mbelchev I just merged a pull request from another student adding the twitter feed. :sob: No problem I will check this to see whats better :smile:

**Comment by mbelchev** [comment]
Ah sorry for that... :( If you like it merge it or i will try to do something else.

**Comment by roonyh** [comment]
Here's something you can do. You can update your repo and improve the twitter feed widget thats already there? And btw when you use images you have to be aware whether you are allowed to use them legally. It could be the case that they are not free to use. So be careful when using random images from the internet.

**Comment by mbelchev** [comment]
Ok! And this twitter icon(photo) is free. I download it from a website which provides free icons.

**Comment by roonyh** [comment]
awsome! can you give me link to that site?

**Comment by mbelchev** [comment]
Of course, will include it in the next request. 
Now i am fixing current twitter feed. Its soo wrong :(

**Pull request closed without merging**
