### PR TITLE
Adding communties table under map

### PR DESCRIPTION
**Pull request by namangoel1**
[Demo](http://namangoel1.github.io/fossasia.github.io).

Using @samarjeet27's code as per http://www.google-melange.com/gci/task/view/google/gci2014/5837190613434368

### CODE REVIEW

**Comment by mariobehling** [comment]
follow up task is here: http://www.google-melange.com/gci/task/edit/google/gci2014/5822449211932672

Improve the design of the community list on fossasia.github.io by

```
Making small icons for social networks, web, email links etc.
Decreasing size of area used by community by decreasing the font size
Enhancing table design e.g. by implementing a color change on mouse over etc.
Adding the country behind the city name, e.g. "Bangalore, India"
Enabling show on map with a button/icon in last "social media" column
```

**Comment by namangoel1** [comment]
@mariobehling The last two might not be possible, Mario, but I'll do as much as I can asap. Thanks! 

Would be great if you could close the task, too: http://www.google-melange.com/gci/task/view/google/gci2014/5837190613434368

**Comment by samarsault** [comment]
@mariobehling, see the wrapper http://fossasia.net/map/ffGeoJsonp.php?callback=generateTable, the data doesn't contain the country's name / code, only the 

Searching a database for every city in country would be tedious, only if the jsonp wrapper is modified to include the country name then it may be possible because the API files contain the country code

**Comment by namangoel1** [comment]
@mariobehling Done what was possible in https://github.com/fossasia/fossasia.github.io/pull/266#

**Pull request merged**
