### PR TITLE
Added Jatin.png and Updated index.html

### PR DESCRIPTION
**Pull request by jatinluthra14**

### CODE REVIEW

**Comment by namangoel1** [comment]
Could you perhaps update with proper indenting?

**Comment by mariobehling** [comment]
@namangoel1 The student's work seems good as he is a beginner. Please help to merge it. Cheers.

**Comment by namangoel1** [comment]
@mariobehling Sure!

**Comment by namangoel1** [comment]
@jatinluthra14 Merged changes.

@mariobehling Thanks, will keep this in mind for the future students as well. Not sure why I am not able to merge this through github, locking manually for now.

**Pull request merged**
