### PR TITLE
Added photo and information

### PR DESCRIPTION
**Pull request by apoorvkh**

### CODE REVIEW

**Comment by namangoel1** [comment]
Please add your information to the bottom, instead of the very top. It is unfair for everyone.

**Comment by samarjeet27** [comment]
Here you go ! https://www.google-melange.com/gci/task/view/google/gci2014/5257295269199872

**Comment by apoorvkh** [comment]
Sorry I don't see how it is unfair, but that was not intended. I have made the change.

**Comment by namangoel1** [comment]
@apoorvk Thanks!

**Comment by roonyh** [comment]
I dont see a image here?

**Comment by namangoel1** [comment]
@RoonyH yup sorry, just reverted. 

@apoorvk, please add an image and remove the thumbs.db file too introduced in https://github.com/apoorvk/fossasia.github.io/commit/e1dd1cae26ea5e85912cb41fb6f8e52fe457f6c6

**Comment by roonyh** [comment]
@namangoel1 how did the test passed?

**Comment by namangoel1** [comment]
@RoonyH I didn't consider checking if the image was actually there. I'll fix and create a pull request.

**Comment by apoorvk** [comment]
I corrected this, adding another pull request, removing Thumbs.db and adding the correct image. Will you please merge this again?

**Comment by apoorvkh** [comment]
Sorry for the mistake, since you closed this, I have created a new pull request with the proper image and data.

**Pull request merged**
