### PR TITLE
Fixing student's image to a reasonable filesize and squaring dimensions

### PR DESCRIPTION
**Pull request by namangoel1**
As the title says.

### CODE REVIEW

**Comment by jtrosclair** [comment]
Thanks for taking the time to do this for me, I was about to do this myself and checked here and it was already done.

**Comment by roonyh** [comment]
@namangoel1 Thanks! hey, what is the task you are working on now?

**Comment by namangoel1** [comment]
@RoonyH welcome :D 

I've prepared draft one for http://www.google-melange.com/gci/task/view/google/gci2014/6097057089585152 but it seems that my claim hasn't been accepted nor the mentor was able to review this yet.

**Comment by roonyh** [comment]
@namangoel1 Hey! I see that your task is reviewed. Meanwhile how would you like to host your code for [nodejs mailer](http://www.google-melange.com/gci/task/view/google/gci2014/5238853300387840) in a fossasia repository and develop it further with the support of other students?

**Comment by namangoel1** [comment]
@RoonyH Thank you! Working on the mailer sounds interesting. Files available here: https://github.com/namangoel1/gci/tree/master/mailer

What should I do to add it to the fossasia repo? afaik I can't 'selectively' push/pull to a repo through git?

**Comment by roonyh** [comment]
I added it here: https://github.com/fossasia/mailer
And [committed your work](https://github.com/fossasia/mailer/commit/9ca3efa5f33478f969bb646588dd41e38d5daf7f) setting you as the author so you get credit for your nice work. :smile:

**Comment by namangoel1** [comment]
@RoonyH Awesome, thank you! Do let me know how could I help there.

**Pull request merged**
